[BaseFlow]
rho=0.110790417259
p=1991.193014318490
U=[958.090507772702,0.0]
gamma=1.4

[[Sources]]
Type="SingleWave"
Amplitude=1.0
Frequency=1000.0
DirVectors=[-1.0,0.5]
Phase=0.0
Speed='S'

[[Sources]]
Type="WaveSpectrum"
Amplitudes= [     10.0,         10.0 ]
Frequencies=[   2000.0,       1000.0 ]
DirVectors= [[1.0,1.0],   [-1.0,-1.0]] 
Phases=     [      0.0,         56.0 ]
Speeds=     [      'S',          'F' ]

[[Sources]]
Type="PSD"
ScaleFactor=1.0
PhaseSeed=1
Speed='S'

InputPSD.Type="PiecewiseLogLog" # or PiecewiseLinear
InputPSD.Data.X=[1e3, 10e3, 100e3, 500e3]
InputPSD.Data.Y=[1e3, 10e3, 100e3, 500e3]
# or
# InputPSD.Type="FromCSV"
# InputPSD.Data.File="csv_file.csv"

Discretization.Min=1e2
Discretization.Max=200e3
Discretization.N=100
Discretization.Interval="Midpoint" # or MidpointLog10

Discretization.Method.Type="RandomLog"
Discretization.Method.Seed=15
# or
# Discretization.Method.Type="Random"
# Discretization.Method.Seed=15

Direction.Type="RandomXYAngle"
Direction.MinAngle=20.0
Direction.MaxAngle=40.0
Direction.Seed=17
# or
# Direction.Type="Constant"
# Direction.Vector=[1.0,1.0,1.0]

# Leave out if not using...
TransferFunction.Type="LowFrequencyLimit"
# or
# TransferFunction.Type="Input"
# TransferFunction.InputTF.Type="PiecewiseLinear" # or PiecewiseLogLog
# ... and all other Function settings
# or
# TransferFunction.Type="FlowNormalFit"
# TransferFunction.ShockStandoffDist=1e-3

[Computation]
t0=0.0

[preCICE]
ParticipantName="Jabber"
ConfigFile="../precice-config.xml"
MeshAccessRegion=[-0.01,1.01, -0.01,1.01]
FluidMeshName="InletSponge"
