[BaseFlow]
rho=0.110790417259
p=1991.193014318490
U=[958.090507772702,0.0]
gamma=1.4

[[Sources]]
Type="SingleWave"
Amplitude=1.0
Frequency=1000.0
Direction=[-1.0,0.5]
Phase=0.0
Speed="Slow"

[Computation]
t0=0.0

[preCICE]
ParticipantName="Jabber"
ConfigFile="../precice-config.xml"
MeshAccessRegion=[-0.01,1.01, -0.01,1.01]
FluidMeshName="InletSponge"
