[BaseFlow]
rho=0.110790417259
p=1991.193014318490
U=[958.090507772702,0.0]
gamma=1.4

[[Sources]]
Type="WaveSpectrum"
Amplitudes= [     10.0,         10.0 ]
Frequencies=[   2000.0,       1000.0 ]
Directions= [[1.0,1.0],  [-1.0, -1.0]] 
Phases=     [      0.0,         56.0 ]
Speeds=     [   "Slow",       "Slow" ]

[TransferFunction]
Type="None"

[Computation]
t0=0.0
Data=["p'"]
Nondimensionalization="None"

[preCICE]
ParticipantName="Jabber"
ConfigFile="../precice-config.xml"
MeshAccessRegion=[-0.01,1.01, -0.01,1.01]
FluidMeshName="Square"
